DocFlow/ViewModels/Services/ServiceSearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DocFlow.ViewModels.Services
{
    public class ServiceSearchModel
    {
        public string Name { get; set; }

    }
}

DocFlow/ViewModels/Services/ServiceSearchRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DocFlow.ViewModels.Services
{
    public class ServiceSearchRecord
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Database { get; set; }
    }
}

DocFlow/Controllers/ServicesController.cs
using DocFlow.ViewModels.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocFlow.Controllers
{
    public class ServicesController : BaseController
    {
        public ActionResult Search()
        {
            ServiceSearchModel model = new ServiceSearchModel();
            return View(model);
        }
        public ActionResult DoSearch(ServiceSearchModel model)
        {
            List<ServiceSearchRecord> results = ServicesService.SearchServices();
            return PartialView("~/Views/Services/Partial/SearchResults.cshtml",results);
        }
        public ActionResult New()
        {
            return View(new ServiceSearchRecord());
        }

        public ActionResult Save(ServiceSearchRecord model)
        {
           model.Id= ServicesService.AddNew(model);
            return Json(model.Id, JsonRequestBehavior.AllowGet);
        }
    }
}

DocFlow/Controllers/TableController.cs
using DocFlow.Data.Texts;
using DocFlow.ViewModels.Table;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DocFlow.Controllers
{
    public class TableController : BaseController
    {
        // GET: Table
        public ActionResult Index()
        {
            return View();
        }

        #region Texts

        public ActionResult Text()
        {
            List<TextModel> m = TextService.GetTexts();
            ViewBag.TextTypes = TextService.GetTextTypes();
            return View(m);
        }

        public ActionResult UpdateText(TextModel value)
        {
            TextService.CRUDText(value, 3);
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public ActionResult InsertText(TextModel value)
        {
            TextService.CRUDText(value, 1);
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RemoveText(int key)
        {
            TextService.CRUDText(new TextModel { Id = key }, 4);
            List<TextModel> m = TextService.GetTexts();
            return Json(m, JsonRequestBehavior.AllowGet);
        }

        #endregion
        
        public ActionResult Template()
        {
            return View();
        }

        public ActionResult Models()
        {
            return View(new ModelsSearchModel());
        }

        public ActionResult DoSearch(ModelsSearchModel model)
        {
            //List<DocumentLineModel> list = ProductService.SearchProducts(model.Code, model.Customer, model.Description);
            //return PartialView("~/Views/Table/Partial/ModelsList.cshtml", list);
            return Content("");
        }

        public ActionResult ModelDetails(long id)
        {
            //ProductEditModel m = new ProductEditModel(ProductService.GetProduct(id));
            //return View(m);
            return Content("");
        }

        public ActionResult TableEdit()
        {
            List<Data.TableEdit> gen = new List<Data.TableEdit>();

            gen = SPService.GetTablesEdit();

            ViewBag.TablesEdit = gen;
            return View();
        }
    }
}

DocFlow/Views/Services/New.cshtml
@model DocFlow.ViewModels.Services.ServiceSearchRecord

@{
    ViewBag.Title = "Novo Serviço";
}


<div class="page-content">
    <h3 class="page-title">
        <i class="fa fa-building-o" style="font-size:28px;"></i> Novo Serviço <small> </small>
    </h3>

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">@Language.HOME</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="fa fa-building-o"></i>
                <a href="@Url.Action("Search", "Services")">Serviços</a>

            </li>
        </ul>
        @*<div class="page-toolbar">
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-fit-height @Css.GoToClass dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                        @Language.GOTO <i class="fa fa-angle-down"></i>
                    </button>
                    @*<ul class="dropdown-menu pull-right" role="menu">
                            <li>
                                <a href="@Url.Action("Models", "Table")"><i class="fa fa-plus"></i> Nova</a>
                            </li>
                        </ul>
                </div>
            </div>*@
    </div>


    <!-- BEGIN Portlet PORTLET-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box @Css.SearchParamsClass" id="search-inputs-pnl">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-search"></i>@Language.NEW
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    <div class="form-body">
                        @using (Html.BeginForm("Save", "Services", FormMethod.Post, new { @class = "horizontal-form", @id = "bs-SingleSearchForm" }))
                        {
                            <input type="hidden" id="Id", name="Id" value="@Model.Id" />
                            <div id="bs-single-search-params-container">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label">Código</label>
                                            @Html.TextBoxFor(m => m.Code, new { @class = "form-control", @placeholder = "Código" })
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label">Nome</label>
                                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Nome" })
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label">Base de Dados</label>
                                            @Html.TextBoxFor(m => m.Database, new { @class = "form-control", @placeholder = "Base de Dados" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <div class="form-actions left " style="background-color:#fff;">
                        <button type="button" id="bs-submit-btn" class="btn purple">@Language.SAVE</button>
                        <button type="button" id="bs-clean-btn" class="btn red-stripe default">@Language.CLEAN</button>
                    </div>

                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
    </div>
</div>


@section Scripts {


    <script src="~/Scripts/Services/services.new.js"></script>
    <script>
        jQuery(document).ready(function () {
            ServicesNew.init();
        });
    </script>
}

DocFlow/Views/Services/Search.cshtml
@model DocFlow.ViewModels.Services.ServiceSearchModel
@{
    ViewBag.Title = "Pesquisa Serviços";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-content">
    <h3 class="page-title">
        <i class="fa fa-book" style="font-size:28px;"></i> Pesquisa Serviços <small> </small>
    </h3>

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">@Language.HOME</a>
                <i class="fa fa-angle-right"></i>
            </li>
        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-fit-height @Css.GoToClass dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                    @Language.GOTO <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a href="@Url.Action("New", "Services")"><i class="fa fa-plus"></i> Novo</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <!-- BEGIN Portlet PORTLET-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box @Css.SearchParamsClass" id="search-inputs-pnl">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-search"></i>@Language.SEARCH_PORTLET_TITLE
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <!-- BEGIN FORM-->
                    <div class="form-body">
                        @using (Html.BeginForm("DoSearch", "Services", FormMethod.Post, new { @class = "horizontal-form", @id = "bs-SingleSearchForm" }))
                        {
                            <div id="bs-single-search-params-container">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group ">
                                            <label class="control-label">Nome</label>
                                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                    }
                    </div>
                    <div class="form-actions left " style="background-color:#fff;">
                        <button type="button" id="bs-submit-btn" class="btn purple">@Language.SEARCH</button>
                        <button type="button" id="bs-clean-btn" class="btn red-stripe default">@Language.CLEAN</button>
                    </div>
                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
        <div class="clearfix"></div>
        <div class="col-md-12" id="div-results">


        </div>
    </div>
</div>

@section Scripts {

  
    <script src="~/Scripts/Services/services.search.js"></script>
    <script>
        jQuery(document).ready(function () {
            ServicesSearch.init();
        });
    </script>
}