DocFlow/ViewModels/Roles/RoleEditModel.cs
using DocFlow.DAL;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace DocFlow.ViewModels
{
    public class RoleEditModel
    {
        //private ApplicationDBContext context = new ApplicationDBContext();

        public RoleEditModel()
        {
            this.Groups = new List<GroupActionRecord>() { };
        }

        public RoleEditModel(int roleid)
            : this()
        {
            using (ApplicationDBContext context = new ApplicationDBContext())
            {
                var role = context.AppRoles.First(x => x.Id == roleid);
                this.RoleID = role.Id;
                this.RoleName = role.Name;
                this.RoleDescription = role.Description;
                this.IsActive = role.IsActive;
                foreach (var item in context.AppActionGroups.Where(x => x.IsActive && x.MainActionGroupID == null).ToList())
                {
                    var group = new GroupActionRecord
                    {
                        GroupDescription = item.Description,
                        GroupID = item.Id,
                        GroupName = item.Name
                    };
                    foreach (var item2 in context.AppActionGroups.Where(x => x.IsActive && x.MainActionGroupID == item.Id).ToList())
                    {
                        var subgroup = new SubGroupActionRecord
                        {
                            GroupDescription = item2.Description,
                            GroupID = item2.Id,
                            GroupName = item2.Name,
                            GroupId = group.GroupID
                        };
                        /*foreach (var item3 in item2.Actions.Where(x=>x.IsActive).Select(x=>x.AppActionGroup).Distinct().ToList())
                        {
                            var action = new ActionRecord
                            {
                                ActionDescription = item3.Description,
                                ActionID = item3.Id,
                                ActionName = item3.Name,
                                HaveActive = role.AppRoleActionGroups.Select(x=>x.AppActionGroupId).Contains(item3.Id),
                                SubGroupId = subgroup.GroupID
                            };
                            subgroup.Actions.Add(action);
                        }*/
                        group.SubGroups.Add(subgroup);
                    }
                    this.Groups.Add(group);

                }
            }
        }

        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public bool IsActive { get; set; }
        [UIHint("GroupActionRecord")]
        public List<GroupActionRecord> Groups { get; set; }
    }

    public class GroupActionRecord
    {
        public GroupActionRecord()
        {
            this.SubGroups = new List<SubGroupActionRecord> { };
        }
        
        public List<SubGroupActionRecord> SubGroups { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
    }

    public class SubGroupActionRecord
    {
        public SubGroupActionRecord()
        {
            this.Actions = new List<ActionRecord> { };
        }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public List<ActionRecord> Actions { get; set; }
        public int GroupId { get; set; }
    }

    public class ActionRecord
    {
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public string ActionDescription { get; set; }
        public bool HaveActive { get; set; }
        public int SubGroupId { get; set; }
    }









}

DocFlow/ViewModels/Roles/RolesSearchRecord.cs
namespace DocFlow.ViewModels
{
    public class RolesSearchRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}

DocFlow/Controllers/AdminController.cs
using DocFlow.Services;
using System.Web.Mvc;

namespace DocFlow.Controllers
{
    [AuthorizeUser]
    public class AdminController : Controller
    {
        //
        // GET: /Permission/

        public ActionResult Index()
        {
            return View();
        }

        [AuthorizeActions("ADM_USR_ROLE_SEARCH")]
        public ActionResult Roles()
        {
            RolesService service = new RolesService();
            return View(service.Search());
        }

        [AuthorizeActions("ADM_USR_SEARCH")]
        public ActionResult Users()
        {
            UserService service = new UserService();
            return View(service.Search());
        }

    }
}

DocFlow/Controllers/RolesController.cs
using DocFlow.Services;
using DocFlow.ViewModels;
using System.Web.Mvc;

namespace DocFlow.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        //
        // GET: /Roles/

        public ActionResult Index()
        {
            return View();
        }

        [AuthorizeActions("ADM_USR_ROLE_NEW")]
        public ActionResult New()
        {
            RolesService service = new RolesService();
            UserProfileEditModel model = new UserProfileEditModel();
            model.ActionsGroups = service.GetAllActionsGroups();
            return View(model);
        }

        [AuthorizeActions("ADM_USR_ROLE_EDIT")]
        public ActionResult Edit(int roleid)
        {
            RolesService service = new RolesService();
            UserProfileEditModel model = service.GetRoleDetails(roleid, true);
            return View(model);
        }

        [HttpPost]
        [AuthorizeActions("ADM_USR_ROLE_EDIT", "ADM_USR_ROLE_NEW")]
        public ActionResult Save(UserProfileEditModel role)
        {
            RolesService service = new RolesService();
            service.SaveRole(role);
            return Json(role.Id, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeActions("ADM_USR_ROLE_VIEW")]
        public ActionResult Details(int roleid)
        {
            RolesService service = new RolesService();
            UserService uservice = new UserService();
            UserProfileEditModel model = service.GetRoleDetails(roleid, false);
            model.Users = uservice.SearchUsersByRole(roleid);
            return View(model);
        }

         [AuthorizeActions("ADM_USR_ROLE_DEL")]
        public ActionResult Delete(int roleid)
        {
            RolesService service = new RolesService();
            service.DeleteRole(roleid);
            return RedirectToAction("Details", new { roleid = roleid });
        }

    }
}

DocFlow/Views/Roles/Edit.cshtml
@model DocFlow.ViewModels.UserProfileEditModel
@{
    ViewBag.Title = @Language.ADMIN_ROLES_PAGE_TITLE;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style {

}
<div class="page-content">
    <h3 class="page-title">
        <i class="icon-user-following" style="font-size:28px;"></i> @Language.ADMIN_ROLES_HEADER <small> @Language.EDITION</small>
    </h3>

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">@Language.HOME</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="fa fa-cogs"></i>
                <a href="@Url.Action("Index", "Admin")">@Language.ADMIN_ROLES_GOTO_HOME</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="icon-user-following"></i>
                <a href="#">@Language.MENU_ADMIN_ROLES</a>
            </li>

        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-fit-height @Css.SearchParamsClass dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                    @Language.GOTO <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">

                    <li>
                        <a href="@Url.Action("Index", "Admin")"> <i class="fa fa-cogs"></i> @Language.ADMIN_ROLES_GOTO_HOME </a>
                    </li>

                    @if (User.IsInAction("ADM_USR_SEARCH"))
                    {
                        <li>
                            <a href="@Url.Action("Users", "Admin")"> <i class="icon-users"></i> @Language.MENU_ADMIN_USERS </a>
                        </li>
                    }
                    @if (User.IsInAction("ADM_USR_ROLE_NEW"))
                    {
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("New", "Roles")"> <i class="fa fa-plus"></i> @Language.ADMIN_ROLES_GOTO_NEW_ROLE </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>


    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-user-following"></i>   @Language.ADMIN_USERS_ROLE
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <form action="#" id="rolesEditForm" class="form-horizontal">
                <div class="form-body">
                    <br />
                    <input type="hidden" name="RoleId" id="RoleId" value="@Model.Id" />
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.NAME</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.DESCRIPTION</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.ACTIVE</label>
                                <div class="col-md-9">
                                    <div class="checkbox-list">
                                        <label class="checkbox-inline">
                                            @Html.CheckBoxFor(m => m.Active)
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12">
                            <div class="portlet">
                                <div class="portlet-title">
                                    <div class="caption">
                                        @Language.ACTIONS
                                    </div>
                                </div>
                                <div class="portlet-body ">

                                    <table class="table dataTable table-bordered table-hover" id="actions_table">
                                        <thead>
                                            <tr>
                                                <th>

                                                </th>
                                                <th>
                                                    @Language.NAME
                                                </th>
                                                <th>
                                                    @Language.DESCRIPTION
                                                </th>
                                                <th>
                                                    @Language.PERMISSION
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var action in Model.ActionsGroups.Where(o => !o.ParentId.HasValue))
                                            {
                                                <tr data-id="@action.Id" data-is-parent="1" data-code="@action.Code" class="parent ">
                                                    <td style="width:50px;">
                                                        <span class=" row-details row-details-close"> </span>
                                                    </td>
                                                    <td class="col-md-5">
                                                        <b> @action.Name</b>
                                                    </td>
                                                    <td class="col-md-5">@action.Description</td>
                                                    <td class="col-md-1"><input type="checkbox" @if (action.Permission) {  <text> checked="checked" </text>                     } data-id="@action.Id" class="check check-parent check-parent-@action.Id" /> </td>
                                                </tr>

                                                foreach (var child in Model.ActionsGroups.Where(o => o.ParentId == action.Id))
                                                {
                                                    <tr data-id="@child.Id" data-is-parent="0" data-parent-id="@child.ParentId" data-code="@child.Code" style="display:none;" class="child child-@child.ParentId">
                                                        <td class="col-md-1"></td>
                                                        <td class="col-md-5">
                                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @child.Name
                                                        </td>
                                                        <td class="col-md-5">@child.Description</td>

                                                        <td class="col-md-1"><input type="checkbox" @if (child.Permission) {  <text> checked="checked" </text>                    } data-id="@child.Id" class="check check-child check-child-@child.ParentId" /> </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions left " style="background-color:#fff;">
                    <button type="button" id="btnSaveRole" class="btn purple">@Language.SAVE</button>
                    <a id="btnCancel" href="@Url.Action("Roles", "Admin")" class="btn red-stripe default">@Language.CANCEL</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/Scripts/Administration/admin.roles.edit.js"></script>

    <script>
        jQuery(document).ready(function () {
            Roles.init();

        });
    </script>
}

DocFlow/Views/Roles/New.cshtml
@model DocFlow.ViewModels.UserProfileEditModel
@{
    ViewBag.Title = @Language.ADMIN_ROLES_PAGE_TITLE;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style {
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />

    <!-- END PAGE LEVEL STYLES -->
}
<div class="page-content">
    <h3 class="page-title">
        <i class="icon-user-following" style="font-size:28px;"></i> @Language.ADMIN_ROLES_HEADER <small> @Language.EDITION</small>
    </h3>

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="/">@Language.HOME</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="fa fa-cogs"></i>
                <a href="@Url.Action("Index", "Admin")">@Language.MENU_ADMIN</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <i class="icon-user-following"></i>
                <a href="#">@Language.ADMIN_ROLES_HEADER</a>
            </li>

        </ul>
        <div class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn btn-fit-height @Css.SearchParamsClass dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                    @Language.GOTO <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li>
                        <a href="@Url.Action("Index", "Admin")"> <i class="fa fa-cogs"></i> @Language.ADMIN_ROLES_GOTO_HOME </a>
                    </li>
                    @if (User.IsInAction("ADM_USR_SEARCH"))
                    {
                        <li>
                            <a href="@Url.Action("Users", "Admin")"> <i class="icon-users"></i> @Language.MENU_ADMIN_USERS </a>
                        </li>
                    }
                    @if (User.IsInAction("ADM_USR_ROLE_NEW"))
                    {
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("New", "Roles")"> <i class="fa fa-plus"></i> @Language.ADMIN_ROLES_GOTO_NEW_ROLE </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>


    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-user-following"></i>   @Language.ADMIN_USERS_ROLE
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <form action="#" id="rolesEditForm" class="form-horizontal">
                <div class="form-body">
                    <br />
                    <input type="hidden" name="RoleId" id="RoleId" value="@Model.Id" />
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.NAME</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.DESCRIPTION</label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-md-3 control-label">@Language.ACTIVE</label>
                                <div class="col-md-9">
                                    <div class="checkbox-list">
                                        <label class="checkbox-inline">
                                            @Html.CheckBoxFor(m => m.Active)
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12">
                            <div class="portlet">
                                <div class="portlet-title">
                                    <div class="caption">
                                        @Language.ACTIONS
                                    </div>
                                </div>
                                <div class="portlet-body ">

                                    <table class="table dataTable table-bordered table-hover" id="actions_table">
                                        <thead>
                                            <tr>
                                                <th>

                                                </th>
                                                <th>
                                                    @Language.NAME
                                                </th>
                                                <th>
                                                    @Language.DESCRIPTION
                                                </th>
                                                <th>
                                                    @Language.PERMISSION
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var action in Model.ActionsGroups.Where(o => !o.ParentId.HasValue))
                                            {
                                                <tr data-id="@action.Id" data-is-parent="1" data-code="@action.Code" class="parent ">
                                                    <td style="width:50px;">
                                                        <span class=" row-details row-details-close"> </span>
                                                    </td>
                                                    <td class="col-md-5">
                                                        <b> @action.Name</b>
                                                    </td>
                                                    <td class="col-md-5">@action.Description</td>
                                                    <td class="col-md-1"><input type="checkbox" @if (action.Permission) {  <text> checked="checked" </text>                      } data-id="@action.Id" class="check check-parent check-parent-@action.Id" /> </td>
                                                </tr>

                                                foreach (var child in Model.ActionsGroups.Where(o => o.ParentId == action.Id))
                                                {
                                                    <tr data-id="@child.Id" data-is-parent="0" data-parent-id="@child.ParentId" data-code="@child.Code" style="display:none;" class="child child-@child.ParentId">
                                                        <td class="col-md-1"></td>
                                                        <td class="col-md-5">
                                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @child.Name
                                                        </td>
                                                        <td class="col-md-5">@child.Description</td>

                                                        <td class="col-md-1"><input type="checkbox" @if (child.Permission) {  <text> checked="checked" </text>                     } data-id="@child.Id" class="check check-child check-child-@child.ParentId" /> </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions left " style="background-color:#fff;">
                    <button type="button" id="btnSaveRole" class="btn purple">@Language.SAVE</button>
                    <a id="btnCancel" href="@Url.Action("Roles", "Admin")" class="btn red-stripe default">@Language.CANCEL</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/Scripts/Administration/admin.roles.new.js"></script>

    <script>
        jQuery(document).ready(function () {
            Roles.init();
        });
    </script>
}